engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: .eslintrc.js
  fixme:
    enabled: true
ratings:
  paths:
    - angular-number-input.js
exclude_paths:
  - test/**/*
  - test/*
  - project/**/*
  - project/*
  - example/**/*
  - example/*
  - docs/**/*
  - docs/*
  - Gruntfile.js
  - karma.conf.js
  - .eslintrc.js
  - .editorconfig
  - .codeclimate.yml
  - LICENSE
  - README.md
  - bower.json
  - package.json
  - .*.json
  - .*.yml
  - .*rc
