name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      uses: browser-actions/setup-chrome@latest
      with:
        args: npm install
    - name: Run CI
      uses: browser-actions/setup-chrome@latest
      with:
        args: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: './coverage/lcov.info'
